# Model configuration
model_name: "conformer-based-classifier-for-anti-spoofing"
eer_files_dir: "./eer_files"

# Dataset configurations
datasets:
  # Example 1: Include all samples (no pattern filtering)
  - name: "asvspoof_2021_DF"

  # Example 2: Filter by file extension
  - name: "academicodec_hifi_16k_320d"
    include_patterns:
      - ".wav"  # Only evaluate wav files

  # Example 3: Filter by speaker IDs
  - name: "vctk"
    include_patterns:
      - "p227"  # Only evaluate samples from speaker p227
      - "p228"  # Only evaluate samples from speaker p228

  # Example 4: Multiple pattern types
  - name: "librispeech_test_clean"
    include_patterns:
      - ".flac"     # Only flac files
      - "61-70968"   # From specific speaker
      - "session1"   # From specific session 