model_name: "tcm_add" #"SCL-Deepfake-audio-detection" #"tcm_add" #"conformer-based-classifier-for-anti-spoofing"
eer_files_dir: "eer_files_600"

# List of datasets to evaluate with their specific configurations
datasets:
  - name: "asvspoof2021_df"
  - name: "ami_ihm"
  - name: "ami_sdm"
  - name: "asvspoof2019_la"
  - name: "emofake"
  - name: "librispeech_test_clean"
  - name: "librispeech_test_other"
  - name: "llamapartialspoof_r01tts0a"
  - name: "llamapartialspoof_r01tts0b"
  - name: "vctk"